FROM adoptopenjdk/openjdk11-openj9:alpine-jre
ARG JAR_FILE=target/gamewatch-game-news-service-0.0.1-SNAPSHOT.jar
WORKDIR /opt/app
COPY ${JAR_FILE} app.jar
ENTRYPOINT [ "java", "-Xsoftmx32m", "-Xmx48m", "-Xss256k", "-Xtune:virtualized", "-XX:+CompactStrings", "-Xshareclasses:name=gamenews,cacheDir=/opt/app/jvm/openj9/shareclasses,verbose", "-Xscmx128m", "-jar", "app.jar" ]
EXPOSE 8082
